brew "bat"
brew "bazelisk"
brew "biome"
brew "buildifier"
brew "cmake"
brew "coreutils"
brew "difftastic"
brew "direnv"
brew "dive"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "fzy"
brew "gh"
brew "git-delta"
brew "git-lfs"
brew "git"
brew "glow"
brew "gnupg"
brew "gnutls"
brew "gpg"
brew "grc"
brew "grex"
brew "gum"
brew "helix"
brew "httpie"
brew "hyperfine"
brew "jq"
brew "just"
brew "lazygit"
brew "libyaml"
brew "mas"
brew "miniserve"
brew "mise"
brew "mole"
brew "procs"
brew "rclone"
brew "readline"
brew "rename"
brew "ripgrep"
brew "rm-improved"
brew "sd"
brew "starship"
brew "stow"
brew "tailspin"
brew "tealdeer"
brew "television"
brew "terminal-notifier"
brew "tokei"
brew "unbound"
brew "vhs"
brew "volta"
brew "watchexec"
brew "watchman"
brew "webp"
brew "yazi"
brew "yq"
brew "zellij"
brew "zoxide"

cask "1password"
cask "alacritty"
cask "audio-hijack"
cask "cleanshot"
cask "farrago"
cask "figma"
cask "firefox"
cask "fission"
cask "forklift"
cask "ghostty"
cask "iina"
cask "loopback"
cask "jordanbaird-ice"
cask "raycast"
cask "rectangle-pro"
cask "soundsource"
cask "visual-studio-code"
cask "visual-studio-code@insiders"

mas "Amphetamine", id: 937984704
mas "Bear", id: 1091189122
mas "DaisyDisk", id: 411643860
mas "Dropover", id: 1355679052
mas "iA Writer", id: 775737590
mas "Keka", id: 470158793
mas "Things", id: 904280696
