# https://github.com/alacritty/alacritty/blob/master/alacritty.yml
live_config_reload: true

import:
  - /.alacritty-theme.yml

window:
  dimensions:
    columns: 80
    lines: 25
  padding:
    x: 5
    y: 5
  # decorations: buttonless
  dynamic_title: true

font:
  normal:
    family: CommitMono
    # family: PragmataPro Mono Liga
    # family: Berkeley Mono
  size: 12
  # use_thin_strokes: true
  offset:
    y: 4

cursor:
  style: Beam

# scrolling:
#   history: 50000

mouse:
  hide_when_typing: false

# Shell
#
# You can set `shell.program` to the path of your favorite shell, e.g.
# `/bin/fish`. Entries in `shell.args` are passed unmodified as arguments to the
# shell.
#
# Default:
#   - (Linux/BSD/macOS) `$SHELL` or the user's login shell, if `$SHELL` is unset
#   - (Windows) powershell
shell:
  program: /opt/homebrew/bin/fish
#  args:
#    - --login

key_bindings:
  - { key: N, mods: Command, action: CreateNewWindow }
