live_config_reload = true

import = [
  "~/.config/alacritty/dracula.toml"
]

[shell]
program = "/opt/homebrew/bin/fish"
args = ["-i"]

[window]
dimensions = { columns = 80, lines = 20 }
padding = { x = 8, y = 8 }

[font]
normal = { family = "PragmataPro Mono Liga", style = "Regular" }
bold = { family = "PragmataPro Mono Liga", style = "Bold" }
italic = { family = "PragmataPro Mono Liga", style = "Italic" }
bold_italic = { family = "PragmataPro Mono Liga", style = "Bold Italic" }
size = 12
offset = { y = 4 }

[cursor]
style = { shape = "Beam", blinking = "On" }

[mouse]
hide_when_typing = false

[keyboard]
bindings = [
{ key = "[", mods = "Command", action = "SelectPreviousTab" },
{ key = "]", mods = "Command", action = "SelectNextTab" },
{ key = "n", mods = "Super", action = "SpawnNewInstance" },
]
