[colors]
cursor = { text = "CellBackground", cursor = "CellForeground" }
vi_mode_cursor = { text = "CellBackground", cursor = "CellForeground" }
footer_bar = { background = "#22212C", foreground = "#F8F8F2" }
line_indicator = { foreground = "None", background = "None" }
selection = { text = "CellForeground", background = "#454158" }

[colors.primary]
background = "#22212C"
foreground = "#F8F8F2"
bright_foreground = "#FFFFFF"

[colors.search]
matches = { foreground = "#454158", background = "#8AFF80" }
focused_match = { foreground = "#454158", background = "#8AFF80" }

[colors.hints]
start = { foreground = "#22212C", background = "#FFFF80" }
end = { foreground = "#FFFF80", background = "#22212C" }

[colors.normal]
black = "#7970A9"
red = "#FF9580"
green = "#8AFF80"
yellow = "#FFFF80"
blue = "#9580FF"
magenta = "#FF80BF"
cyan = "#80FFEA"
white = "#F8F8F2"

[colors.bright]
black = "#7970A9"
red = "#FFAA99"
green = "#A2FF99"
yellow = "#FFFF99"
blue = "#AA99FF"
magenta = "#FF99CC"
cyan = "#99FFEE"
white = "#FFFFFF"
