# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format="$all"

right_format = """$status$cmd_duration"""

[git_branch]
symbol = " "

[git_status]
untracked = "⚑"
deleted = "✕"
modified = "±"

[character]
format = "$symbol "
success_symbol = "[❯](white)"
error_symbol = "[❯](red)"

